DROP TABLE IF EXISTS `update`;
CREATE TABLE `Update` (
    `UpdateID` INT PRIMARY KEY AUTO_INCREMENT,
    `LastLoginTime` TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;